//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11
#![allow(unused)]
pub mod prelude;

pub mod account;
pub mod data_middleware;
pub mod download_middleware;
pub mod module;
pub mod platform;
pub mod rel_account_platform;
pub mod rel_module_account;
pub mod rel_module_data_middleware;
pub mod rel_module_download_middleware;
pub mod rel_module_platform;

pub use account::{
    Column as AccountColumn, Entity as AccountEntity,
    Model as AccountModel,
};

pub use data_middleware::{
    Column as DataMiddlewareColumn,
    Entity as DataMiddlewareEntity, Model as DataMiddlewareModel,
};

pub use download_middleware::{
    Column as DownloadMiddlewareColumn,
    Entity as DownloadMiddlewareEntity, Model as DownloadMiddlewareModel,
};

pub use module::{
    Entity as ModuleEntity,
    Model as ModuleModel,
};

pub use platform::{
    Column as PlatformColumn, Entity as PlatformEntity,
    Model as PlatformModel,
};

pub use rel_account_platform::{
    Column as RelAccountPlatformColumn,
    Entity as RelAccountPlatformEntity, Model as RelAccountPlatformModel,
};

pub use rel_module_account::{
    Column as RelModuleAccountColumn,
    Entity as RelModuleAccountEntity, Model as RelModuleAccountModel,
};

pub use rel_module_data_middleware::{
    Column as RelModuleDataMiddlewareColumn,
    Entity as RelModuleDataMiddlewareEntity, Model as RelModuleDataMiddlewareModel,
};

pub use rel_module_download_middleware::{
    Column as RelModuleDownloadMiddlewareColumn, Entity as RelModuleDownloadMiddlewareEntity,
    Model as RelModuleDownloadMiddlewareModel,
};

pub use rel_module_platform::{
    Column as RelModulePlatformColumn,
    Entity as RelModulePlatformEntity, Model as RelModulePlatformModel,
};
