//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::account::Entity as Account;
pub use super::data_middleware::Entity as DataMiddleware;
pub use super::download_middleware::Entity as DownloadMiddleware;
pub use super::module::Entity as Module;
pub use super::platform::Entity as Platform;
pub use super::rel_account_platform::Entity as RelAccountPlatform;
pub use super::rel_module_account::Entity as RelModuleAccount;
pub use super::rel_module_data_middleware::Entity as RelModuleDataMiddleware;
pub use super::rel_module_download_middleware::Entity as RelModuleDownloadMiddleware;
pub use super::rel_module_platform::Entity as RelModulePlatform;
