//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "crawler", table_name = "data_table_update_record")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub platform: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub module: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub schema: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub table_name: String,
    pub update_at: DateTime,
    pub max_date: Option<Date>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
