//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::data_table_update_record::Entity as DataTableUpdateRecord;
pub use super::data_table_update_record::ActiveModel as DataTableUpdateRecordActiveModel;
pub use super::data_table_update_record::Column as DataTableUpdateColumn;