//! mocra-store: mocra's multi-tenant metadata entities (sea-orm, extracted from the main crate).
//!
//! The `account × platform × module` model + data/download middleware + relation tables + task
//! results / logs. Entities generated by sea-orm-codegen: a pure data layer (zero crawler /
//! engine coupling), used by the `store` feature.

pub mod entity;

pub use entity::*;
